name: Stock Analysis and Telegram Notifications

on:
  schedule:
    - cron: '30 3 * * *' # Runs daily at 9 AM IST (3:30 AM UTC)
  workflow_dispatch: # Allows manual triggering

jobs:
  analyze-and-notify:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Install system dependencies for fbprophet
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev g++

      # Set up Python 3.8 (stable for fbprophet==0.7.1)
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      # Cache pip dependencies
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the analysis script
      - name: Run stock analysis
        run: |
          python nifty50_analysis.py

      # Notify on failure
      - name: Notify Telegram on failure
        if: failure()
        run: |
          curl -s -X POST "https://api.telegram.org/bot8017759392:AAEwM-W-y83lLXTjlPl8sC_aBmizuIrFXnU/sendMessage" \
            -d chat_id="711856868" \
            -d text="⚠️ Stock Analysis Workflow failed. Please check GitHub Actions logs." \
            -d parse_mode="MarkdownV2"
